version: '3'

services:

  mc:
    build: .
    depends_on:
      - 'db'
    ports:
      - '3005:3005'

  db:
    image: postgres
    environment:
      POSTGRES_USER: fairtest
      POSTGRESS_PASSWORD: seniortable
